repos:
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
        - "--line-length=80"
        - "--force-grid-wrap=1"
        - "--profile=black"

  # black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args:
          - "--line-length=80"

  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=80"
          - "--extend-ignore=E203"
          # Force Flake8 to use the exit status code 0 even if there are errors.
          - "--exit-zero"
        verbose: true
