paths:
  base_path: /data/user/mwolf/data/
  output_dir: /data/user/chaack/skyllh
analysis:
  name: NorthernTracks_v003p00_KDE_PDF_v003
  datasets: IC79 IC86 MC
  default_source:
    ra: 77.358
    dec: 5.693
  livetime: 10


